### ISSUE TITLE
http_poller in a clustered logstash?

### ISSUE THREAD

**Issue by blysik** [logstash-plugins/logstash-input-http_poller#33]
This is getting ahead of things, but I hear that logstash is moving in the direction of clustering logstash nodes.

What does that mean for this plugin?  How will you manage only having a single logstash node do a poll?

**Comment by andrewvc** [comment]
@blysik It's a great question, but a bit earlier to answer considering there's nothing too concrete yet for clustered logstash. I'm going to close this question for now since we'll be reviewing plugins one by one later for issues related to this once we know more about what clustered logstash will be.
