### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-input-http_poller#6]
This thing needs tests!

**Comment by maximede** [comment]
Let's discuss what tests we need

* happy path
* When remote server doesn't answer ( wrong dns/ timeout )
* When remote server respond with an error code ( 404/500/... ) 
* When we receive something else than what the configured codec wants ( html instead of json by example )
* What if the request takes more time than the configured timeout

**Comment by andrewvc** [comment]
Those all sound good @maximede !

**Comment by andrewvc** [comment]
@maximede Is there a subset of tests you'd like to tackle? We can collaborate here and split up the work.

**Comment by maximede** [comment]
I think I'll have time this week-end to tackle the list by myself.
The only test that seems a bit trickier for me is the one request time vs timeout

**Comment by maximede** [comment]
Actually, what could be really helpful for me is if you could write some kind of template for the tests. Ruby is not my main language, and I may lose some time trying to figure out how to mock the different kind of inputs.

**Comment by maximede** [comment]
I’ve started writing some test and I’ve hit a small problem.
The fact that the run method contains a "Stud.interval(@interval) do” seems to make the plugin not that easy to test.

The way I’m currently bypassing this problem is that I’ve extracted the content of the Stud_interval inside a public method named run_once(queue) and I’m directly testing this method.

I don’t really like the fact that the method is public but I don’t know if there is a better way to test.

What do you think ?

**Comment by andrewvc** [comment]
Hey @maximede we should submit changes via PR now that we've got some initial code in the repo, which is our general practice for official Logstash plugins. No worries on your last push, but given that we have something that runs up at this point that's a good strategy.

Speaking of, I've got a mega PR up that addresses this ticket and some others. I took your tests as a base and added onto them. I did rewrite them to follow betterspecs guidelines however. You can find that PR here: https://github.com/logstash-plugins/logstash-input-http_poller/pull/10 . 

I'd love your feedback on the proposed changes.

**Comment by maximede** [comment]
Ok, I'll submit a PR next time.
Thanks for refactoring my code, and sorry if it was a bit messy, I'm still not really used to ruby dev ^^

**Comment by andrewvc** [comment]
Thanks , my apologies for not letting you know. I shouldn't have been
pushing directly either. I'm glad to help you with any ruby questions you
have! Your help has been much appreciated!

**Comment by elvarb** [comment]
* SSL errors (when support for that comes https://github.com/logstash-plugins/logstash-input-http_poller/issues/2 )
* DNS errors, unable to resolve, unable to query DNS

**Comment by andrewvc** [comment]
This should all be covered in https://github.com/logstash-plugins/logstash-input-http_poller/pull/10
